# Generated by Django 3.2.3 on 2021-05-17 16:40

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilerequirement',
            name='profile_type',
            field=models.CharField(choices=[(core.models.ProfileRequirement.ProfileChoices['OB'], 'obligatori'), (core.models.ProfileRequirement.ProfileChoices['EX'], 'exempció'), (core.models.ProfileRequirement.ProfileChoices['BO'], 'bonificació del 50%')], default=None, max_length=30, verbose_name='profile_type'),
        ),
    ]
