# Generated by Django 3.2 on 2021-05-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolment',
            name='uf',
            field=models.ManyToManyField(null=True, to='core.UF'),
        ),
    ]
