# Generated by Django 3.2 on 2021-04-29 15:06

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolment',
            name='state',
            field=models.CharField(choices=[(core.models.ValidationState['P'], 'Pendent'), (core.models.ValidationState['V'], 'Validat'), (core.models.ValidationState['U'], 'Failed')], default=None, max_length=20, verbose_name='estat de matrícula'),
        ),
    ]
