# Generated by Django 3.2 on 2021-06-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolment',
            name='ralc_num',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Identificador RALC'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='request_num',
            field=models.CharField(max_length=100, unique=True, verbose_name='Número de sol·licitud'),
        ),
    ]
