# Generated by Django 3.2 on 2021-06-06 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210604_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='end',
        ),
        migrations.RemoveField(
            model_name='career',
            name='start',
        ),
    ]
