# Generated by Django 3.2 on 2021-05-12 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_enrolment_uf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolment',
            name='tutor_1',
        ),
        migrations.RemoveField(
            model_name='enrolment',
            name='tutor_2',
        ),
    ]
