# Generated by Django 3.2 on 2021-05-10 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210510_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uf',
            name='term',
        ),
    ]
