# Generated by Django 3.2 on 2021-06-07 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210606_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolment',
            name='emergency_number',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name="número d'emergència"),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='excursions',
            field=models.BooleanField(blank=True, null=True, verbose_name="Salides d'excursio"),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='extracurricular',
            field=models.BooleanField(blank=True, null=True, verbose_name='Salides extraescolars'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='image_rights',
            field=models.BooleanField(blank=True, null=True, verbose_name="Drets d'imatge"),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='profile_req',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profilerequirement'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='state',
            field=models.CharField(choices=[('P', 'Pendent'), ('V', 'Validat'), ('R', 'Rebutjat')], default='P', max_length=20, verbose_name='estat de matrícula'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='tutor_1_dni',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='dni del pare/mare o tutor/a legal (1)'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='tutor_1_lastname1',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='cognoms del pare/mare o tutor/a legal (1)'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='tutor_1_lastname2',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='cognoms del pare/mare o tutor/a legal (1)'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='tutor_1_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='nom del pare/mare o tutor/a legal (1)'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='tutor_2_dni',
            field=models.CharField(blank=True, default=None, max_length=9, null=True, verbose_name='dni del pare/mare o tutor/a legal (2)'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='tutor_2_lastname1',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='cognoms del pare/mare o tutor/a legal (2)'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='tutor_2_lastname2',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='cognoms del pare/mare o tutor/a legal (2)'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='tutor_2_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='cognoms del pare/mare o tutor/a legal (2)'),
        ),
    ]
