# Generated by Django 3.2 on 2021-06-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210607_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolment',
            name='last_name_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='cognom 2'),
        ),
    ]
