# Generated by Django 3.2 on 2021-05-06 15:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_profilerequirement_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilerequirement',
            name='profile_type',
            field=models.CharField(choices=[(core.models.ProfileRequirement.ProfileChoices['EX'], 'exemption'), (core.models.ProfileRequirement.ProfileChoices['BO'], 'bonus')], default=None, max_length=9, verbose_name='profile_type'),
        ),
    ]
