# Generated by Django 3.2 on 2021-05-13 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_enrolment_profile_req'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.term'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='career',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.career'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='profile_req',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profilerequirement'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='record',
            name='uf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.uf'),
        ),
        migrations.AlterField(
            model_name='req_enrol',
            name='enrolment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.enrolment'),
        ),
        migrations.AlterField(
            model_name='req_enrol',
            name='requirement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.requirement'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profilerequirement'),
        ),
        migrations.AlterField(
            model_name='uf',
            name='mp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mp'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='req_enrol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.req_enrol'),
        ),
    ]
