# Generated by Django 3.2 on 2021-05-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_profilerequirement_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilerequirement',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nom'),
        ),
    ]
