# Generated by Django 3.2 on 2021-05-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_profilerequirement_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolment',
            name='excursions',
            field=models.BooleanField(null=True, verbose_name="Salides d'excursio"),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='extracurricular',
            field=models.BooleanField(null=True, verbose_name='Salides extraescolars'),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='image_rights',
            field=models.BooleanField(null=True, verbose_name="Drets d'imatge"),
        ),
    ]
