# Generated by Django 3.2 on 2021-05-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210507_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolment',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='adreça'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='city',
            field=models.CharField(max_length=150, null=True, verbose_name='ciutat'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='correu'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='emergency_number',
            field=models.CharField(max_length=14, null=True, verbose_name="número d'emergència"),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='phone_number',
            field=models.CharField(max_length=14, null=True, verbose_name='número de telèfon'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='postal_code',
            field=models.CharField(max_length=5, null=True, verbose_name='codi postal'),
        ),
    ]
