# Generated by Django 3.2 on 2021-05-07 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210507_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolment',
            name='career',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.career'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='dni',
            field=models.CharField(max_length=9, null=True, verbose_name='dni'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.term'),
        ),
    ]
