# Generated by Django 3.2 on 2021-05-07 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210507_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolment',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.profilerequirement'),
        ),
    ]
